/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steuerung_ControllerInfo */

#ifndef _Included_steuerung_ControllerInfo
#define _Included_steuerung_ControllerInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steuerung_ControllerInfo
 * Method:    initController
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steuerung_ControllerInfo_initController
(JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    deleteController
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steuerung_ControllerInfo_deleteController
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_isConnected
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_A
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1A
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_B
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1B
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_X
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1X
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_Y
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1Y
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_D_UP
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1D_1UP
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_D_DOWN
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1D_1DOWN
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_D_LEFT
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1D_1LEFT
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_D_RIGHT
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1D_1RIGHT
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_START
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1START
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_BACK
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1BACK
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_TH_RIGHT
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1TH_1RIGHT
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_TH_LEFT
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1TH_1LEFT
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_SH_RIGHT
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1SH_1RIGHT
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getGamepad_SH_LEFT
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steuerung_ControllerInfo_getGamepad_1SH_1LEFT
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getTrigger_LEFT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steuerung_ControllerInfo_getTrigger_1LEFT
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getTrigger_RIGHT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steuerung_ControllerInfo_getTrigger_1RIGHT
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getThumb_LX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steuerung_ControllerInfo_getThumb_1LX
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getThumb_LY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steuerung_ControllerInfo_getThumb_1LY
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getThumb_RX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steuerung_ControllerInfo_getThumb_1RX
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    getThumb_RY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steuerung_ControllerInfo_getThumb_1RY
  (JNIEnv *, jobject);

/*
 * Class:     steuerung_ControllerInfo
 * Method:    Vibrate
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_steuerung_ControllerInfo_Vibrate
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
