/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_koehlert_camera_Tester */

#ifndef _Included_com_koehlert_camera_Tester
#define _Included_com_koehlert_camera_Tester
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
