/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_koehlert_serialcomm_Communicator */

#ifndef _Included_com_koehlert_serialcomm_Communicator
#define _Included_com_koehlert_serialcomm_Communicator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_koehlert_serialcomm_Communicator
 * Method:    init
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_koehlert_serialcomm_Communicator_init
  (JNIEnv *, jobject, jobject, jobject, jint, jint);

/*
 * Class:     com_koehlert_serialcomm_Communicator
 * Method:    transceive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_koehlert_serialcomm_Communicator_transceive
  (JNIEnv *, jobject);

/*
 * Class:     com_koehlert_serialcomm_Communicator
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_koehlert_serialcomm_Communicator_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
