/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hardware_communication_SPIComm */

#ifndef _Included_hardware_communication_SPIComm
#define _Included_hardware_communication_SPIComm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hardware_communication_SPIComm
 * Method:    init
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_hardware_communication_SPIComm_init
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint);

/*
 * Class:     hardware_communication_SPIComm
 * Method:    transmit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hardware_communication_SPIComm_transmit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
