/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hardware_communication_Arduino */

#ifndef _Included_hardware_communication_Arduino
#define _Included_hardware_communication_Arduino
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hardware_communication_Arduino
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hardware_communication_Arduino_init
  (JNIEnv *, jobject);

/*
 * Class:     hardware_communication_Arduino
 * Method:    spi
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_hardware_communication_Arduino_spi
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
